FROM ubuntu:20.04

RUN apt-get update && apt-get -y install \
    curl \
    wget \
    nano \
    sudo \
    lynx \
    bash-completion \
    zip \
    unzip \
    gnupg \
    psmisc \
    dpkg \
    apt \
    lsb-release \
    apt-transport-https \
    ca-certificates
